set nocompatible " use vim defaults
filetype plugin indent on

"
" vim-plug
"
call plug#begin('~/.vim/bundle')

Plug 'dense-analysis/ale'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align'
Plug 'mkitt/tabline.vim'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'

call plug#end()

set signcolumn=yes
set completeopt=menu,menuone,noselect
set complete+=.,w,b,u,t  " standard completion sources
set pumheight=10         " limit popup height

"
" cursor
"
let &t_EI = "\e[1 q" " normal, blinking block (default)
let &t_SI = "\e[6 q" " insert, steady bar (xterm)
let &t_SR = "\e[4 q" " replace, steady underline

"
" basic settings
"
syntax on         " turn syntax highlighting on by default
set termguicolors " use 24-bit color

"
" shell
"
set shell=/bin/zsh

set encoding=utf-8 " set default encoding to UTF-8
set scrolloff=3    " keep 3 lines when scrolling
set mouse=a        " a: all; n: normal; v: visual

set autoread   " reload changes
set showcmd    " display incomplete commands
set number     " show line numbers
set ruler      " show the current row and column
set splitbelow " show split window on the bottom
set hidden     " allow switching buffers without saving

"
" folding
"
set foldmethod=indent
set foldlevelstart=6

"
" backup, swap and undo
"
set noswapfile
set nobackup
set undofile
set undodir=~/.vim/undo

"
" spaces and tabs
"
set nowrap
set autoindent
set smarttab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab                   " use spaces, not tabs
set backspace=indent,eol,start  " make that backspace key work the way it should

"
" invisibles / whitespaces
"
set list                  " show invisible characters
set listchars=            " reset the listchars
set listchars+=tab:»\     " show tab spaces as »
set listchars+=extends:›  " show ‹ or › when characters are not displayed on the left or right
set listchars+=precedes:‹ " show ‹ or › when characters are not displayed on the left or right
set listchars+=nbsp:·     " show whitespace as ·
set listchars+=trail:·    " show trailing spaces as ·

"
" visual assist
"
set cursorline     " highlight current line

"
" status line
"
set laststatus=2
set statusline+=\ %<%t%m%r%h%w                    " File path, modified, readonly, helpfile, preview
set statusline+=%=                                " Right Side
set statusline+=\ %{FugitiveStatusline()}
set statusline+=\ %3l,%-3v                        " Colomn number
set statusline+=\ %Y                              " FileType
set statusline+=\ %{''.(&fenc!=''?&fenc:&enc).''} " Encoding
set statusline+=\ (%{&ff})                        " FileFormat (dos/unix..)
set statusline+=\ %3p%%                           " Line number / total lines, percentage of document
set statusline+=\ %-2n                            " Buffer number

"
" search settings
"
set hlsearch   " highlight searches
set incsearch  " do incremental searching
set showmatch  " jump to matches when entering regexp
set ignorecase " ignore case when searching
set smartcase  " no ignorecase if Uppercase char present

"
" annoying features
"
set belloff=all

"
" wildmenu
"
set wildmenu        " enable wildmenu for completion
set wildoptions=pum " display a vertical menu

"
" ignore list
"
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz
set wildignore+=*/tmp/*,*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/sorbet/*,*/.sass-cache/*
set wildignore+=*.swp,*~,._*

"
" colors & themes
"
colorscheme default
highlight SignColumn ctermbg=NONE " transparent sign column

"
" ALE
"
let g:ale_linters = {
  \ 'ruby':       ['rubocop'],
  \ 'eruby':      ['erubi'],
  \ 'yaml':       ['prettier'],
  \ 'json':       ['prettier'],
  \ 'javascript': ['prettier'],
  \ 'rust':       ['rustc', 'cargo'],
  \ }

let g:ale_fixers = {
  \ '*':          ['remove_trailing_lines', 'trim_whitespace'],
  \ 'ruby':       ['rubocop'],
  \ 'yaml':       ['prettier'],
  \ 'json':       ['prettier'],
  \ 'javascript': ['prettier'],
  \ 'rust':       ['rustfmt'],
  \}

let g:ale_fix_on_save = 1
let g:ale_rust_cargo_use_check = 1

"
" asyncomplete
"
au User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#buffer#get_source_options({
  \ 'name': 'buffer',
  \ 'allowlist': ['*'],
  \ 'completor': function('asyncomplete#sources#buffer#completor'),
  \ }))

"
" key mappings
"
let mapleader = ' '

"
" FZF fuzzy finder
"
nmap <Leader>f :GFiles<CR>
nmap <Leader>ff :Files<CR>
nmap <Leader>b :Buffers<CR>
nmap <Leader>h :History<CR>

"
" EasyAlign
"
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)

nmap <leader>hs :set hlsearch! hlsearch?<CR>  " toggle hlsearch with <leader>hs
nmap <silent> <leader>cd :lcd %:h<CR>         " cd to the directory containing the file in the buffer

" native completion navigation
inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"
inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"
inoremap <expr> <TAB> pumvisible() ? "\<C-y>" : "\<TAB>"
